export const data = [
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
    {
        id_solicitud: "5849",
        estado_reg: "activo",
        id_solicitud_ext: null,
        presu_revertido: null,
        fecha_apro: "2019-12-17",
        estado: "liberacion",
        id_funcionario_aprobador: "254",
        id_moneda: "1",
        id_gestion: "3",
        tipo: "Servicio",
        num_tramite: "ADQ-002266-2019",
        justificacion: "Control de audiometría anual (revisión de oído externo e interno, capacidad auditiva, radiografía ecoauditiva y otros relacionados a la actividad laboral de cada funcionario de Regional La Paz)",
        id_depto: "12",
        lugar_entrega: "Consultorio médico de audiometría",
        extendida: "no",
        posibles_proveedores: null,
        id_proceso_wf: "260317",
        comite_calificacion: null,
        id_categoria_compra: "1",
        id_funcionario: "555",
        id_estado_wf: "895016",
        fecha_soli: "2019-12-17",
        fecha_reg: "2019-12-17 17:51:33.072822",
        id_usuario_reg: "335",
        fecha_mod: "2019-12-17 17:55:49.969095",
        id_usuario_mod: "335",
        usr_reg: "jose.morales",
        usr_mod: "jose.morales",
        id_uo: "648",
        desc_funcionario: "JOSE LUIS MORALES ANGULO",
        desc_funcionario_apro: "MARCELO JOSE HINOJOSA TORRICO",
        desc_uo: "GOM-GERENCIA DE OPERACIONES Y MANTENIMIENTO",
        desc_gestion: "2019",
        desc_moneda: "BS",
        desc_depto: "ADQ-LP",
        desc_proceso_macro: "Adquisiciones",
        desc_categoria_compra: "Categoría I",
        id_proceso_macro: "25",
        numero: "ADQ-LP-SOLC-12/4-2019",
        desc_funcionario_rpc: null,
        obs: "Solicitud a espera de aprobación #ADQ-LP-SOLC-12/4-2019",
        instruc_rpc: null,
        desc_proveedor: null,
        id_proveedor: null,
        id_funcionario_supervisor: null,
        desc_funcionario_supervisor: null,
        ai_habilitado: "no",
        id_cargo_rpc: null,
        id_cargo_rpc_ai: null,
        tipo_concepto: "servicio",
        revisado_asistente: "no",
        fecha_inicio: "2019-12-18",
        dias_plazo_entrega: "2",
        obs_presupuestos: null,
        precontrato: "no_necesita",
        update_enable: "no",
        codigo_poa: null,
        obs_poa: null,
        contador_estados: "1",
        nro_po: "",
        fecha_po: null,
        importe_total: "2436.00",
        comprometer_87: "no",
        observacion: "Ninguna"
    },
];